version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: go build -v -o api graphic-packs-updater.go
  release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run: |
          go get github.com/aktau/github-release
          github-release --help
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release