version: 2
jobs:
  build:
    docker:
      - image: circleci/go:1.11
    steps:
      - checkout
      - run: go build -v -o api main.go
  release:
    docker:
      - image: circleci/go:1.11
    steps:
      - checkout
      - go get github.com/aktau/github-release
      - run: github-release --help
workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - release